app:
  name: 'Benim Uygulamam'
  version: '1.0.0'

server:
  port: 8084
  host: 'localhost'

database:
  port: 5432
  user: 'myuser'
  password: 'mypassword'
  db: 'chatdb'
  host: 'localhost'

redis:
  redisURL: 'localhost:6379'
  password: ''
  sessiondb: 0
  chatdb: 1

jwt:
  secret: 'secret'
