app:
  name: 'Benim Uygulamam'
  version: '1.0.0'

server:
  port: 8080
  host: 'localhost'

database:
  port: 5432
  user: 'myuser'
  password: 'mypassword'
  db: 'auth'
  host: 'localhost'

redis:
  redisURL: 'localhost:6379'
  password: ''
  db: 0

jwt:
  secret: 'secret'
